version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: .dockerfiles/BackendDev
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/opt/app
    environment:
      MYSQL_ROOT_PASSWORD: db_rootpass
      JWT_SECRET: devsecret
    restart: always
  backend_test:
    build:
      context: ./
      dockerfile: .dockerfiles/BackendDev
    command: yarn run test:watch
    ports:
      - "9005:9005"
    volumes:
      - ./backend:/opt/app
    environment:
      MYSQL_ROOT_PASSWORD: db_rootpass
      JWT_SECRET: devsecret
    restart: always
  db:
    image: mysql:8.0.3
    volumes:
      - /var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./initLoans.sql:/docker-entrypoint-initdb.d/initLoans.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: db_rootpass
      MYSQL_DATABASE: db_1
    restart: always
  mywebsql:
    image: quantumobject/docker-mywebsql
    ports:
      - "9001:80"
    restart: always
